export const CATEGORIES = {
  all: {
    ar: "الكل",
    en: "All",
    de: "Alle",
    ru: "Все",
    fr: "Tout",
    pl: "Wszystko",
    it: "Tutto",
  },
  soups: {
    ar: "شوربات",
    en: "Soups",
    de: "Suppen",
    ru: "Супы",
    fr: "Soupes",
    pl: "Zupy",
    it: "Zuppe",
  },
  salads: {
    ar: "سلطات",
    en: "Salads",
    de: "Salate",
    ru: "Салаты",
    fr: "Salades",
    pl: "Salatki",
    it: "Insalate",
  },
  pizza: {
    ar: "بيتزا",
    en: "Pizza",
    de: "Pizza",
    ru: "Пицца",
    fr: "Pizza",
    pl: "Pizza",
    it: "Pizza",
  },
  mains: {
    ar: "أطباق رئيسية",
    en: "Main Courses",
    de: "Hauptgerichte",
    ru: "Вторые блюда",
    fr: "Plats Principaux",
    pl: "Dania Glowne",
    it: "Piatti Principali",
  },
  desserts: {
    ar: "حلويات",
    en: "Desserts",
    de: "Desserts",
    ru: "Десерты",
    fr: "Desserts",
    pl: "Desery",
    it: "Dolci",
  },
};

export const MENU_ITEMS = [
  // Oriental - Consolidated into one item
  {
    id: 1,
    category: "mains",
    restaurant: "oriental",
    name: {
      ar: "كل الاصناف",
      en: "All Items",
      de: "Alle Artikel",
      ru: "Все элементы",
      fr: "Tous les articles",
      pl: "Wszystkie przedmioty",
      it: "Tutti gli articoli",
    },
    price: 0,
    img: "/oriental_menu.png",
    desc: {
      ar: "المنيو الشرقي كامل لعدد الأفراد المختار",
      en: "Full Oriental Menu for the selected number of guests",
      de: "Vollständiges orientalisches Menü für die ausgewählte Anzahl von Gästen",
      ru: "Полное восточное меню для выбранного количества гостей",
      fr: "Menu oriental complet pour le nombre de convives sélectionné",
      pl: "Pelne menu orientalne dla wybranej liczby gosci",
      it: "Menu orientale completo per il numero di ospiti selezionato",
    },
  },

  // Italian Pizza
  {
    id: 7,
    category: "pizza",
    restaurant: "italian",
    name: {
      ar: "بيتزا مارجريتا",
      en: "PIZZA MARGARITA",
      de: "Pizza Margherita",
      ru: "Пицца Маргарита",
      fr: "Pizza Margarita",
      pl: "Pizza Margarita",
    },
    desc: {
      ar: "صلصة طماطم وجبنة موتزاريلا",
      en: "Served with tomato sauce and mozzarella cheese.",
      de: "Serviert mit Tomatensauce und Mozzarella.",
      ru: "Подается с томатным соусом и сыром моцарелла.",
      fr: "Servie avec sauce tomate et mozzarella.",
      pl: "Podawana z sosem pomidorowym i serem mozzarella.",
      it: "Servita con salsa di pomodoro e mozzarella.",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=400&fm=webp",
  },
  {
    id: 8,
    category: "pizza",
    restaurant: "italian",
    name: {
      ar: "بيتزا خضار",
      en: "PIZZA VEGGIE",
      de: "Pizza Veggie",
      ru: "Вегетарианская пицца",
      fr: "Pizza Végétarienne",
      pl: "Pizza Wegetarianska",
    },
    desc: {
      ar: "خضار موسمي، صلصة طماطم، وموتزاريلا",
      en: "Served with Seasonal Vegetable, tomato sauce and mozzarella cheese.",
      de: "Mit saisonalem Gemüse, Tomatensauce und Mozzarella.",
      ru: "С сезонными овощами, томатным соусом и моцареллой.",
      fr: "Servie avec légumes de saison, sauce tomate et mozzarella.",
      pl: "Podawana z warzywami sezonowymi, sosem pomidorowym i serem mozzarella.",
      it: "Servita con verdure di stagione, salsa di pomodoro e mozzarella.",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?q=80&w=400&fm=webp",
  },
  {
    id: 9,
    category: "pizza",
    restaurant: "italian",
    name: {
      ar: "بيتزا ٤ أجبان",
      en: "PIZZA QUATRO FORMAGGI",
      de: "Pizza Quattro Formaggi",
      ru: "Пицца 4 сыра",
      fr: "Pizza Quatre Fromages",
      pl: "Pizza Cztery Sery",
    },
    desc: {
      ar: "صلصة طماطم و٤ أنواع من الجبنة",
      en: "Served with tomato sauce and 4 kinds of cheese.",
      de: "Mit Tomatensauce und 4 Käsesorten.",
      ru: "С томатным соусом и 4 видами сыра.",
      fr: "Servie avec sauce tomate et 4 sortes de fromages.",
      pl: "Podawana z sosem pomidorowym i 4 rodzajami sera.",
      it: "Servita con salsa di pomodoro e 4 tipi di formaggio.",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400&fm=webp",
  },
  {
    id: 10,
    category: "pizza",
    restaurant: "italian",
    name: {
      ar: "بيتزا تونة",
      en: "PIZZA ALA TUNA",
      de: "Pizza Tonno",
      ru: "Пицца с тунцом",
      fr: "Pizza au Thon",
      pl: "Pizza z Tunczykiem",
    },
    desc: {
      ar: "صلصة مارينارا، تونة، كابري، وجبنة",
      en: "Served with marinara sauce, tuna, capers and cheese.",
      de: "Mit Marinara-Sauce, Thunfisch, Kapern und Käse.",
      ru: "С соусом маринара, тунцом, каперсами и сыром.",
      fr: "Servie avec sauce marinara, thon, câpres et fromage.",
      pl: "Podawana z sosem marinara, tunczykiem, kaparami i serem.",
      it: "Servita con salsa marinara, tonno, capperi e formaggio.",
    },
    price: 0,
    img: "https://plus.unsplash.com/premium_photo-1673439304183-8840bd0dc1bf?q=80&w=400&fm=webp",
  },
  {
    id: 11,
    category: "pizza",
    restaurant: "italian",
    name: {
      ar: "بيتزا مورينو",
      en: "PIZZA MORENO",
      de: "Pizza Moreno",
      ru: "Пицца Морено",
      fr: "Pizza Moreno",
      pl: "Pizza Moreno",
    },
    desc: {
      ar: "سمك، كالاماري، جبنة وزيتون",
      en: "Served with fish, Calamari, Cheese and Olives.",
      de: "Mit Fisch, Calamari, Käse und Oliven.",
      ru: "С рыбой, кальмарами, сыром и оливками.",
      fr: "Servie avec poisson, calamars, fromage et olives.",
      pl: "Podawana z ryba, kalmarami, serem i oliwkami.",
      it: "Servita con pesce, calamari, formaggio e olive.",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=400&fm=webp",
  },

  // Italian Mains
  {
    id: 12,
    category: "mains",
    restaurant: "italian",
    name: {
      ar: "مانزو ال جورجونزولا",
      en: "MANZO AL GORGONZOLA",
      de: "Manzo al Gorgonzola",
      ru: "Манзо аль Горгонзола",
      fr: "Manzo au Gorgonzola",
      pl: "Manzo al Gorgonzola",
    },
    desc: {
      ar: "فيليه لحم بصلصة الفلفل والجبنة الزرقاء، مع بطاطس مهروسة وخضار سوتيه",
      en: "Beef fillet served with Mashed Potato, Vegetable Suttee, Pepper Sauce, Blue cheese Sauce",
      de: "Rinderfilet mit Kartoffelpüree, Gemüse-Suttee, Pfeffersauce und Blauschimmelkäsesauce",
      ru: "Говяжье филе с картофельным пюре, овощами, перечным соусом и соусом из голубого сыра",
      fr: "Filet de boeuf servi avec purée de pommes de terre, légumes sautés, sauce au poivre, sauce au fromage bleu",
      pl: "Filet wolowy podawany z puree ziemniaczanym, warzywami suttee, sosem pieprzowym i sosem z sera gorgonzola",
      it: "Filetto di manzo servito con purè di patate, verdure saltate, salsa al pepe, salsa al gorgonzola",
    },
    price: 0,
    img: "/manzo.webp",
  },
  {
    id: 13,
    category: "mains",
    restaurant: "italian",
    name: {
      ar: "دجاج بانيه إيطالي",
      en: "ITALIAN CHICKEN PANE",
      de: "Italienisches Hühner-Pane",
      ru: "Итальянское куриное филе",
      fr: "Poulet Pané Italien",
      pl: "Wloski Kurczak Panierowany",
    },
    desc: {
      ar: "دجاج بانيه مع بطاطس مهروسة وخضار سوتيه",
      en: "Chicken Pane served with Mashed Potato, Vegetable Suttee",
      de: "Hühner-Pane with Kartoffelpüree and Gemüse-Suttee",
      ru: "Куриное филе с картофельным пюре и овощами",
      fr: "Poulet pané servi avec purée de pommes de terre, légumes sautés",
      pl: "Kurczak panierowany podawany z puree ziemniaczanym, warzywami suttee",
      it: "Pollo impanato servito con purè di patate, verdure saltate",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=400&fm=webp",
  },
  {
    id: 14,
    category: "mains",
    restaurant: "italian",
    name: {
      ar: "سيرنيا آلا ليفورنيز",
      en: "CERNIA ALLA LIVORNESE",
      de: "Cernia alla Livornese",
      ru: "Рыба по-ливорнски",
      fr: "Cernia à la Livournaise",
      pl: "Cernia alla Livornese",
      it: "Cernia alla Livornese",
    },
    desc: {
      ar: "فيليه سمك مشوي على سرير من السبانخ، طماطم، بصل، كابري، وصلصة أعشاب بيضاء",
      en: "Grilled fish fillet on a bed of sautéed spinach, tomatoes, onions, capers and white herbs sauce",
      de: "Gegrilltes Fischfilet auf sautiertem Spinat, Tomaten, Zwiebeln, Kapern und weißer Kräutersauce",
      ru: "Жареное рыбное филе на подушке из обжаренного шпината, помидоров, лука, каперсов и белого соуса с травами",
      fr: "Filet de poisson grillé sur un lit d'épinards sautés, tomates, oignons, câpres et sauce aux herbes blanches",
      pl: "Grillowany filet rybny na podlozu z smazonego szpinaku, pomidorow, cebuli, kaparow i bialego sosu ziolowego",
      it: "Filetto di pesce grigliato su un letto di spinaci saltati, pomodori, cipolle, capperi e salsa bianca alle erbe",
    },
    price: 0,
    img: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=400&fm=webp",
  },
];
